export const PRODUCT_IMG_SEARCH_REQUEST = "PRODUCT_IMG_SEARCH_REQUEST";
export const PRODUCT_IMG_SEARCH_SUCCESS = "PRODUCT_IMG_SEARCH_SUCCESS";
export const PRODUCT_IMG_SEARCH_FAIL = "PRODUCT_IMG_SEARCH_FAIL";
